services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
  ynabbotservice:
    depends_on:
       - db  
    build:
      context: .
      dockerfile: YnabBotService/Dockerfile
    network_mode: host
    restart: always
    image: ${DOCKER_REGISTRY-}ynabbotservice

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      YNABBOT_PROXY_USE: ${YNABBOT_PROXY_USE}
      YNABBOT_PROXY_HOST: ${YNABBOT_PROXY_HOST}
      YNABBOT_PROXY_PORT: ${YNABBOT_PROXY_PORT}
      YNABBOT_TELEGRAM_TOKEN: ${YNABBOT_TELEGRAM_TOKEN}
      YNAB_CLIENT_ID: ${YNAB_CLIENT_ID}
      YNAB_CLIENT_SECRET: ${YNAB_CLIENT_SECRET}
      YNAB_REDIRECT_URI: ${YNAB_REDIRECT_URI}
      
volumes:
    dbdata:
