using System.Collections.Generic;

namespace Adp.YnabClient.Ynab;

internal static class MccCodes
{
    private static readonly Dictionary< int, string > CodeDescription;

    static MccCodes()
    {
        CodeDescription = new Dictionary< int, string >
        {
            { 742, "Ветеринарные услуги" },
            { 763, "Сельскохозяйственные кооперативы" },
            { 780, "Услуги садоводства и ландшафтного дизайна" },
            { 1520, "Генеральные подрядчики – жилое и коммерческое строительство" },
            { 1711, "Генеральные подрядчики по вентиляции, теплоснабжению и водопроводу" },
            { 1731, "Подрядчики по электричеству" },
            { 1740, "Изоляция, мозаика, штукатурные работы, каменная кладка, облицовка плиткой, кафелем" },
            { 1750, "Столярные работы" },
            { 1761, "Кровельные и сайдинговые работы, обработка листового металла" },
            { 1771, "Подрядчики бетонных работ" },
            { 1799, "Контрактные услуги – нигде более не классифицированные" },
            { 2741, "Различные издательства/ печатное дело" },
            { 2791, "Набор текстов, шрифтов, таблиц и относящиеся к этому услуги" },
            { 2842, "Специальная обработка, полировка, санитария" },
            { 3000, "United Airlines (UNITED)" },
            { 3001, "American Airlines (AMERICAN)" },
            { 3002, "Pan American (PAN AM)" },
            { 3003, "Eurofly (EUROFLY)" },
            { 3004, "Dragonair (DRAGONAIR)" },
            { 3005, "British Airways (BRITISH A)" },
            { 3006, "Japan Air Lines (JAL)" },
            { 3007, "Air France (AIR FRAN)" },
            { 3008, "Lufthansa (LUFTHAN)" },
            { 3009, "Air Canada (AIR CAN)" },
            { 3010, "Royal Dutch Airlines (KLM)" },
            { 3011, "Aeroflot (AEROFLOT)" },
            { 3012, "Qantas (QANTAS)" },
            { 3013, "Alitalia (ALITALIA)" },
            { 3014, "Saudi Arabian Airlines (SAUDI AI)" },
            { 3015, "Swiss International Air Lines (SWISS)" },
            { 3016, "Scandinavian Airline System (SAS)" },
            { 3017, "South African Airways (SAFRICAN)" },
            { 3018, "Varig (Brazil) (VARIG)" },
            { 3019, "Авиалинии, авиакомпании" },
            { 3020, "Air India (AIR-INDI)" },
            { 3021, "Air Algerie (AIRALGER)" },
            { 3022, "Philippine Airlines (PAL AIR)" },
            { 3023, "Mexicana (MEXICANA)" },
            { 3024, "Pakistan International (PAKISTAN)" },
            { 3025, "Air New Zealand Limited International (AIR NZ)" },
            { 3026, "Emirates Airlines (EMIRATES)" },
            { 3027, "Union de Transports Aeriens (UTAAIR)" },
            { 3028, "Air Malta (AIRMALTA)" },
            { 3029, "SN Brussels Airlines (SNBRU AIR)" },
            { 3030, "Aerolineas Argentinas (AERO ARG)" },
            { 3031, "Olympic Airways (OLYMPICA)" },
            { 3032, "El Al (EL AL)" },
            { 3033, "Ansett Airlines (ANSETT)" },
            { 3034, "Etihad Airways (ETIHADAIR)" },
            { 3035, "Tap (Portugal) (TAP)" },
            { 3036, "VASP (Brazil) (VASP)" },
            { 3037, "EgyptAir (EGYPTAIR)" },
            { 3038, "Kuwait Airways (KUWAIT)" },
            { 3039, "Avianca (AVIANCA)" },
            { 3040, "Gulf Air (Bahrain) (GULF AIR)" },
            { 3041, "Balkan—Bulgarian Airlines (BALKAN)" },
            { 3042, "Finnair (FINNAIR)" },
            { 3043, "Aer Lingus (AERLING)" },
            { 3044, "Air Lanka (AIR LANKA)" },
            { 3045, "Nigeria Airways (NIGERIA)" },
            { 3046, "Cruzeiro do Sul (Brazil) (CRUZEIRO)" },
            { 3047, "THY (Turkey) (THY)" },
            { 3048, "Royal Air Maroc (AIRMARO)" },
            { 3049, "Tunis Air (TUNIS AI)" },
            { 3050, "Icelandair (ICELANDA)" },
            { 3051, "Austrian Airlines (AUSTRIAN)" },
            { 3052, "LAN Airlines (LAN AIR)" },
            { 3053, "AVIACO (Spain) (AVIACO)" },
            { 3054, "LADECO (Chile) (LADECO)" },
            { 3055, "LAB (Bolivia) (LAB)" },
            { 3056, "Jet Airways (JET AIR)" },
            { 3057, "Virgin America (VIR AMER)" },
            { 3058, "Delta (DELTA)" },
            { 3059, "DBA Airlines (DBA AIR)" },
            { 3060, "Northwest Airlines (NWA AIR)" },
            { 3061, "Continental (CONTINEN)" },
            { 3062, "Hapag-Lloyd Express (HLX)" },
            { 3063, "U.S. Airways (USAIRWYS)" },
            { 3064, "Adria Airways (ADRIA AIR)" },
            { 3065, "Air Inter (AIRINTER)" },
            { 3066, "Southwest Airlines (SOUTHWES)" },
            { 3067, "Vanguard Airlines (VANGUARD)" },
            { 3068, "Air Astana (AIRSTANA)" },
            { 3069, "Sun Country Airlines (SUNCNTRY)" },
            { 3071, "Air British Columbia (AIR B R C)" },
            { 3072, "Cebu Pacific (CEBU PAC)" },
            { 3073, "Air Cal" },
            { 3075, "Singapore Airlines (SINGAPOR)" },
            { 3076, "Aeromexico (AEROMEXI)" },
            { 3077, "Thai Airways (THAIAIRW)" },
            { 3078, "China Airlines (CHINAAIR)" },
            { 3079, "Jetstar Airways (JETSTAR)" },
            { 3081, "Авиалинии, авиакомпании" },
            { 3082, "Korean Airlines (KOREAN)" },
            { 3083, "Air Afrique (AIR AFRIQ)" },
            { 3084, "Eva Airways (EVA AIR)" },
            { 3085, "Midwest Express Airlines (MIDWEST)" },
            { 3086, "Carnival Airlines" },
            { 3087, "Metro Airlines (METROAI)" },
            { 3088, "Croatia Air (CROATIA)" },
            { 3089, "Transaero (TRANSAERO)" },
            { 3090, "Uni Airways (UNIAIR)" },
            { 3092, "Midway Airlines" },
            { 3093, "Авиалинии, авиакомпании" },
            { 3094, "Zambia Airways (ZAMBIA A)" },
            { 3095, "Авиалинии, авиакомпании" },
            { 3096, "Air Zimbabwe (AIRZIMBA)" },
            { 3097, "Spanair (SPANAIR)" },
            { 3098, "Asiana Airlines (ASIANA)" },
            { 3099, "Cathay Pacific (CATHAYPA)" },
            { 3100, "Malaysian Airline System (MALAY AI)" },
            { 3101, "Авиалинии, авиакомпании" },
            { 3102, "Iberia (IBERIA)" },
            { 3103, "Garuda (Indonesia) (GARUDA)" },
            { 3104, "Авиалинии, авиакомпании" },
            { 3105, "Авиалинии, авиакомпании" },
            { 3106, "Braathens S.A.F.E. (Norway) (BRAATHEN)" },
            { 3107, "Авиалинии, авиакомпании" },
            { 3109, "Авиалинии, авиакомпании" },
            { 3110, "Авиалинии, авиакомпании" },
            { 3111, "British Midland (BRITISH M)" },
            { 3112, "Windward Island (WINDWARD)" },
            { 3113, "Авиалинии, авиакомпании" },
            { 3114, "Авиалинии, авиакомпании" },
            { 3115, "Авиалинии, авиакомпании" },
            { 3116, "Авиалинии, авиакомпании" },
            { 3117, "Venezolana International de Aviacion (VIASA)" },
            { 3118, "Авиалинии, авиакомпании" },
            { 3119, "Авиалинии, авиакомпании" },
            { 3120, "Авиалинии, авиакомпании" },
            { 3121, "Авиалинии, авиакомпании" },
            { 3122, "Авиалинии, авиакомпании" },
            { 3123, "Авиалинии, авиакомпании" },
            { 3124, "Авиалинии, авиакомпании" },
            { 3125, "Tan Airlines (TAN AIR)" },
            { 3126, "Авиалинии, авиакомпании" },
            { 3127, "Taca International (TACA INT)" },
            { 3128, "Авиалинии, авиакомпании" },
            { 3129, "Surinam Airways (SURINAM)" },
            { 3130, "Sunworld International Airways (SUNWORLD)" },
            { 3131, "VLM Airlines (VLM)" },
            { 3132, "Frontier Airlines (FRONTIER)" },
            { 3133, "Авиалинии, авиакомпании" },
            { 3134, "Авиалинии, авиакомпании" },
            { 3135, "Авиалинии, авиакомпании" },
            { 3136, "Qatar Airways Company W.L.L. (QATAR AIR)" },
            { 3137, "Авиалинии, авиакомпании" },
            { 3138, "Авиалинии, авиакомпании" },
            { 3139, "Авиалинии, авиакомпании" },
            { 3140, "Авиалинии, авиакомпании" },
            { 3141, "Авиалинии, авиакомпании" },
            { 3142, "Авиалинии, авиакомпании" },
            { 3143, "Авиалинии, авиакомпании" },
            { 3144, "Virgin Atlantic (VIR ATL)" },
            { 3145, "Авиалинии, авиакомпании" },
            { 3146, "Luxair (LUXAIR)" },
            { 3147, "Авиалинии, авиакомпании" },
            { 3148, "Air Littoral, S.A. (LITTORAL)" },
            { 3150, "Авиалинии, авиакомпании" },
            { 3151, "Air Zaire (AIRZAIRE)" },
            { 3152, "Авиалинии, авиакомпании" },
            { 3153, "Авиалинии, авиакомпании" },
            { 3154, "Авиалинии, авиакомпании" },
            { 3155, "Авиалинии, авиакомпании" },
            { 3156, "GO FLY Ltd. (GOFLY)" },
            { 3157, "Авиалинии, авиакомпании" },
            { 3158, "Авиалинии, авиакомпании" },
            { 3159, "Provincetown-Boston Airways (PBA)" },
            { 3160, "Авиалинии, авиакомпании" },
            { 3161, "All Nippon Airways (ANAAIR)" },
            { 3162, "Авиалинии, авиакомпании" },
            { 3163, "Авиалинии, авиакомпании" },
            { 3164, "Norontair (NORONTAI)" },
            { 3165, "Авиалинии, авиакомпании" },
            { 3166, "Авиалинии, авиакомпании" },
            { 3167, "Aero Continente (AERO CONT)" },
            { 3168, "Авиалинии, авиакомпании" },
            { 3169, "Авиалинии, авиакомпании" },
            { 3170, "Авиалинии, авиакомпании" },
            { 3171, "Canadian Airlines (CANADIAN)" },
            { 3172, "Nation Air (NATIONAI)" },
            { 3173, "Авиалинии, авиакомпании" },
            { 3174, "JetBlue Airways (JETBLUE)" },
            { 3175, "Middle East Air (MIDEASTA)" },
            { 3176, "Авиалинии, авиакомпании" },
            { 3177, "AirTran Airways (AIRTRAN A)" },
            { 3178, "Mesa Air (MESA AIR)" },
            { 3179, "Авиалинии, авиакомпании" },
            { 3180, "Westjet Airlines (WESTJET)" },
            { 3181, "Malev Hungarian Airlines (MALEV)" },
            { 3182, "LOT – Polish Airlines (LOT)" },
            { 3183, "Oman Aviation Services (OMAN AIR)" },
            { 3184, "LIAT (LIAT)" },
            { 3185, "LAV Linea Aeropostal Venezolana (LAV)" },
            { 3186, "LAP Lineas Aereas Paraguayas (LAP)" },
            { 3187, "LACSA (Costa Rica) (LACSA)" },
            { 3188, "Virgin Express (VIR EXP)" },
            { 3189, "Авиалинии, авиакомпании" },
            { 3190, "Jugoslav Air (JUGOSLAV)" },
            { 3191, "Island Airlines (ISLANDAI)" },
            { 3192, "Авиалинии, авиакомпании" },
            { 3193, "Indian Airlines (INDIAN A)" },
            { 3194, "Авиалинии, авиакомпании" },
            { 3195, "Авиалинии, авиакомпании" },
            { 3196, "Hawaiian Air (HAWAIIAN)" },
            { 3197, "Havasu Airlines (HAVASUAI)" },
            { 3198, "Авиалинии, авиакомпании" },
            { 3199, "Servicios Aereos Militares" },
            { 3200, "Guyana Airways (GUYANA A)" },
            { 3201, "Авиалинии, авиакомпании" },
            { 3202, "Авиалинии, авиакомпании" },
            { 3203, "Авиалинии, авиакомпании" },
            { 3204, "Freedom Airlines (FREEDOM)" },
            { 3205, "Авиалинии, авиакомпании" },
            { 3206, "China Eastern Airlines (CHINAEAST)" },
            { 3207, "Авиалинии, авиакомпании" },
            { 3208, "Авиалинии, авиакомпании" },
            { 3209, "Авиалинии, авиакомпании" },
            { 3210, "Авиалинии, авиакомпании" },
            { 3211, "Norwegian Air Shuttle (NORWEGIAN)" },
            { 3212, "Dominicana de Aviacion (DOMINICA)" },
            { 3213, "Malmo Aviation (MALMO AV)" },
            { 3214, "Авиалинии, авиакомпании" },
            { 3215, "Авиалинии, авиакомпании" },
            { 3216, "Авиалинии, авиакомпании" },
            { 3217, "CSA Ceskoslovenske Aerolinie (CSA)" },
            { 3218, "Авиалинии, авиакомпании" },
            { 3219, "Compania Panamena de Aviacion (COPA)" },
            { 3220, "Compania Faucett (COMPANIA)" },
            { 3221, "Transportes Aeros Militares Ecuatorianos (TAME AIR)" },
            { 3222, "Command Airways (COMMAND)" },
            { 3223, "Comair (COMAIR)" },
            { 3224, "Авиалинии, авиакомпании" },
            { 3225, "Авиалинии, авиакомпании" },
            { 3226, "Skyways (SKYWAYS)" },
            { 3227, "Авиалинии, авиакомпании" },
            { 3228, "Cayman Airways (CAYMANAIR)" },
            { 3229, "SAETA (Sociedad Ecuatorianas De Transportes Aereo) (SAETAAIR)" },
            { 3230, "Авиалинии, авиакомпании" },
            { 3231, "SAHSA (Servicio Aero de Honduras) (SAHSA)" },
            { 3232, "Авиалинии, авиакомпании" },
            { 3233, "Авиалинии, авиакомпании" },
            { 3234, "Caribbean Airlines (CARIBBEAN)" },
            { 3235, "Авиалинии, авиакомпании" },
            { 3236, "Air Arabia Airline (AIR ARAB)" },
            { 3237, "Авиалинии, авиакомпании" },
            { 3238, "Авиалинии, авиакомпании" },
            { 3239, "Bar Harbor Airlines (BARHARBO)" },
            { 3240, "Bahamasair (BAHAMASA)" },
            { 3241, "Aviateca (Guatemala) (AVIATECA)" },
            { 3242, "Avensa (AVENSA)" },
            { 3243, "Austrian Air Service (AUSTRAIR)" },
            { 3244, "Авиалинии, авиакомпании" },
            { 3245, "EasyJet (EASYJET)" },
            { 3246, "Ryanair (RYANAIR)" },
            { 3247, "Gol Airlines (GOL)" },
            { 3248, "Tam Airlines (TAM)" },
            { 3249, "Авиалинии, авиакомпании" },
            { 3250, "Авиалинии, авиакомпании" },
            { 3251, "Авиалинии, авиакомпании" },
            { 3252, "ALM Antilean Airlines (ALM)" },
            { 3253, "America West (AMERWEST)" },
            { 3254, "Trump Airline" },
            { 3256, "Alaska Airlines Inc. (ALASKA A)" },
            { 3257, "Авиалинии, авиакомпании" },
            { 3258, "Авиалинии, авиакомпании" },
            { 3259, "Авиалинии, авиакомпании" },
            { 3260, "Spirit Airlines (SPIRIT)" },
            { 3261, "Air China (AIR CHINA)" },
            { 3262, "Авиалинии, авиакомпании" },
            { 3263, "Aero Servicio Carabobo (ASERCA)" },
            { 3264, "Авиалинии, авиакомпании" },
            { 3265, "Авиалинии, авиакомпании" },
            { 3266, "Air Seychelles (AIR SEYC)" },
            { 3267, "Air Panama International (AIR PANA)" },
            { 3268, "Авиалинии, авиакомпании" },
            { 3270, "Авиалинии, авиакомпании" },
            { 3274, "Авиалинии, авиакомпании" },
            { 3275, "Авиалинии, авиакомпании" },
            { 3276, "Авиалинии, авиакомпании" },
            { 3277, "Авиалинии, авиакомпании" },
            { 3278, "Авиалинии, авиакомпании" },
            { 3279, "Авиалинии, авиакомпании" },
            { 3280, "Air Jamaica (AIR JAMA)" },
            { 3281, "Air Djibouti (AIR DJIB)" },
            { 3282, "Air Djibouti (AIR DJIB)" },
            { 3283, "Авиалинии, авиакомпании" },
            { 3284, "Авиалинии, авиакомпании" },
            { 3285, "Aero Peru (AEROPERU)" },
            { 3286, "Aero Nicaraguenses (AERO NIC)" },
            { 3287, "Aero Coach Aviation (AEROCOAC)" },
            { 3288, "Авиалинии, авиакомпании" },
            { 3289, "Авиалинии, авиакомпании" },
            { 3290, "Авиалинии, авиакомпании" },
            { 3291, "Авиалинии, авиакомпании" },
            { 3292, "Cyprus Airways (CYPRUSA)" },
            { 3293, "Ecuatoriana (ECUATORI)" },
            { 3294, "Ethiopian Airlines (ETHIOPIA)" },
            { 3295, "Kenya Airways (KENYAAIR)" },
            { 3296, "Air Berlin (AIRBERLIN)" },
            { 3297, "Tarom Romanian Air Transport (TAROM AIR)" },
            { 3298, "Air Mauritius (AIRMAURI)" },
            { 3299, "Wideroes Flyveselskap (WIDEROES)" },
            { 3351, "A liated Auto Rental" },
            { 3352, "American Intl Rent-a-car" },
            { 3353, "Brooks Rent-a-car" },
            { 3354, "Action Auto Rental" },
            { 3355, "Агентства по аренде автомобилей" },
            { 3356, "Агентства по аренде автомобилей" },
            { 3357, "Hertz Rent-a-car" },
            { 3358, "Агентства по аренде автомобилей" },
            { 3359, "Payless Car Rental" },
            { 3360, "Snappy Car Rental" },
            { 3361, "Airways Rent-a-car" },
            { 3362, "Altra Auto Rental" },
            { 3363, "Агентства по аренде автомобилей" },
            { 3364, "Agency Rent-a-car" },
            { 3365, "Агентства по аренде автомобилей" },
            { 3366, "Budget Rent-a-car" },
            { 3367, "Агентства по аренде автомобилей" },
            { 3368, "Holiday Rent-a-wreck" },
            { 3369, "Агентства по аренде автомобилей" },
            { 3370, "Rent-a-wreck" },
            { 3371, "Агентства по аренде автомобилей" },
            { 3372, "Агентства по аренде автомобилей" },
            { 3373, "Агентства по аренде автомобилей" },
            { 3374, "Агентства по аренде автомобилей" },
            { 3375, "Агентства по аренде автомобилей" },
            { 3376, "Ajax Rent-a-car" },
            { 3377, "Агентства по аренде автомобилей" },
            { 3378, "Агентства по аренде автомобилей" },
            { 3379, "Агентства по аренде автомобилей" },
            { 3380, "Агентства по аренде автомобилей" },
            { 3381, "Europ Car" },
            { 3382, "Агентства по аренде автомобилей" },
            { 3383, "Агентства по аренде автомобилей" },
            { 3384, "Агентства по аренде автомобилей" },
            { 3385, "Tropical Rent-a-car" },
            { 3386, "Showcase Rental Cars" },
            { 3387, "Alamo Rent-a-car" },
            { 3388, "Агентства по аренде автомобилей" },
            { 3389, "Avis Rent-a-car" },
            { 3390, "Dollar Rent-a-car" },
            { 3391, "Europe By Car" },
            { 3392, "Агентства по аренде автомобилей" },
            { 3393, "National Car Rental" },
            { 3394, "Kemwell Group Rent-a-car" },
            { 3395, "Thrifty Rent-a-car" },
            { 3396, "Tilden Tent-a-car" },
            { 3397, "Агентства по аренде автомобилей" },
            { 3398, "Econo-car Rent-a-car" },
            { 3399, "Amerex Rent-a-Car" },
            { 3400, "Auto Host Cost Car Rentals" },
            { 3401, "Агентства по аренде автомобилей" },
            { 3402, "Агентства по аренде автомобилей" },
            { 3403, "Агентства по аренде автомобилей" },
            { 3404, "Агентства по аренде автомобилей" },
            { 3405, "Enterprise Rent-a-car" },
            { 3406, "Агентства по аренде автомобилей" },
            { 3407, "Агентства по аренде автомобилей" },
            { 3408, "Агентства по аренде автомобилей" },
            { 3409, "General Rent-a-car" },
            { 3410, "Агентства по аренде автомобилей" },
            { 3412, "A-1 Rent-a-car" },
            { 3413, "Агентства по аренде автомобилей" },
            { 3414, "Godfrey Natl Rent-a-car" },
            { 3415, "Агентства по аренде автомобилей" },
            { 3416, "Агентства по аренде автомобилей" },
            { 3417, "Агентства по аренде автомобилей" },
            { 3418, "Агентства по аренде автомобилей" },
            { 3419, "Alpha Rent-a-car" },
            { 3420, "Ansa Intl Rent-a-car" },
            { 3421, "Allstae Rent-a-car" },
            { 3422, "Агентства по аренде автомобилей" },
            { 3423, "Avcar Rent-a-car" },
            { 3425, "Automate Rent-a-car" },
            { 3426, "Агентства по аренде автомобилей" },
            { 3427, "Avon Rent-a-car" },
            { 3428, "Carey Rent-a-car" },
            { 3429, "Insurance Rent-a-car" },
            { 3430, "Major Rent-a-car" },
            { 3431, "Replacement Rent-a-car" },
            { 3432, "Reserve Rent-a-car" },
            { 3433, "Ugly Duckling Rent-a-car" },
            { 3434, "USA Rent-a-car" },
            { 3435, "Value Rent-a-car" },
            { 3436, "Autohansa Rent-a-car" },
            { 3437, "Cite Rent-a-car" },
            { 3438, "Interent Rent-a-car" },
            { 3439, "Milleville Rent-a-car" },
            { 3440, "Via Route Rent-a-Car" },
            { 3441, "Агентства по аренде автомобилей" },
            { 3501, "Holiday Inns" },
            { 3502, "Best Western Hotels" },
            { 3503, "Sheraton Hotels" },
            { 3504, "Hilton Hotels" },
            { 3505, "Forte Hotels" },
            { 3506, "Golden Tulip Hotels" },
            { 3507, "Friendship Inns" },
            { 3508, "Quality Inns" },
            { 3509, "Marriott Hotels" },
            { 3510, "Days Inn" },
            { 3511, "Arabella Hotels" },
            { 3512, "Inter-continental Hotels" },
            { 3513, "Westin Hotels" },
            { 3514, "Отели, мотели, курорты" },
            { 3515, "Rodeway Inns" },
            { 3516, "La Quinta Motor Inns" },
            { 3517, "Americana Hotels" },
            { 3518, "Sol Hotels" },
            { 3519, "Pullman International Hotels" },
            { 3520, "Meridien Hotels" },
            { 3521, "Crest Hotels (see Forte Hotels)" },
            { 3522, "Tokyo Hotel" },
            { 3523, "Pennsula Hotel" },
            { 3524, "Welcomgroup Hotels" },
            { 3525, "Dunfey Hotels" },
            { 3526, "Отели, мотели, курорты" },
            { 3527, "Downtowner-passport Hotel" },
            { 3528, "Red Lion Hotels" },
            { 3529, "Cp Hotels" },
            { 3530, "Renaissance Hotels" },
            { 3531, "Astir Hotels" },
            { 3532, "Sun Route Hotels" },
            { 3533, "Hotel Ibis" },
            { 3534, "Southern Pacific Hotels" },
            { 3535, "Hilton International" },
            { 3536, "Amfac Hotels" },
            { 3537, "Ana Hotel" },
            { 3538, "Concorde Hotels" },
            { 3539, "Отели, мотели, курорты" },
            { 3540, "Iberotel Hotels" },
            { 3541, "Hotel Okura" },
            { 3542, "Royal Hotels" },
            { 3543, "Four Seasons Hotels" },
            { 3544, "Ciga Hotels" },
            { 3545, "Shangri-la International" },
            { 3546, "Отели, мотели, курорты" },
            { 3547, "Отели, мотели, курорты" },
            { 3548, "Hoteles Melia" },
            { 3549, "Auberge Des Governeurs" },
            { 3550, "Regal 8 Inns" },
            { 3551, "Отели, мотели, курорты" },
            { 3552, "Coast Hotels" },
            { 3553, "Park Inns International" },
            { 3554, "Отели, мотели, курорты" },
            { 3555, "Отели, мотели, курорты" },
            { 3556, "Отели, мотели, курорты" },
            { 3557, "Отели, мотели, курорты" },
            { 3558, "Jolly Hotels" },
            { 3559, "Отели, мотели, курорты" },
            { 3560, "Отели, мотели, курорты" },
            { 3561, "Отели, мотели, курорты" },
            { 3562, "Comfort Inns" },
            { 3563, "Journey’s End Motls" },
            { 3564, "Отели, мотели, курорты" },
            { 3565, "Relax Inns" },
            { 3566, "Отели, мотели, курорты" },
            { 3567, "Отели, мотели, курорты" },
            { 3568, "Ladbroke Hotels" },
            { 3569, "Отели, мотели, курорты" },
            { 3570, "Forum Hotels" },
            { 3571, "Отели, мотели, курорты" },
            { 3572, "Miyako Hotels" },
            { 3573, "Sandman Hotels" },
            { 3574, "Venture Inns" },
            { 3575, "Vagabond Hotels" },
            { 3576, "Отели, мотели, курорты" },
            { 3577, "Mandarin Oriental Hotel" },
            { 3578, "Отели, мотели, курорты" },
            { 3579, "Hotel Mercure" },
            { 3580, "Отели, мотели, курорты" },
            { 3581, "Delta Hotel" },
            { 3582, "Отели, мотели, курорты" },
            { 3583, "Sas Hotels" },
            { 3584, "Princess Hotels International" },
            { 3585, "Hungar Hotels" },
            { 3586, "Sokos Hotels" },
            { 3587, "Doral Hotels" },
            { 3588, "Helmsley Hotels" },
            { 3589, "Отели, мотели, курорты" },
            { 3590, "Fairmont Hotels" },
            { 3591, "Sonesta Hotels" },
            { 3592, "Omni Hotels" },
            { 3593, "Cunard Hotels" },
            { 3594, "Отели, мотели, курорты" },
            { 3595, "Hospitality International" },
            { 3596, "Отели, мотели, курорты" },
            { 3597, "Отели, мотели, курорты" },
            { 3598, "Regent International Hotels" },
            { 3599, "Pannonia Hotels" },
            { 3600, "Отели, мотели, курорты" },
            { 3601, "Отели, мотели, курорты" },
            { 3602, "Отели, мотели, курорты" },
            { 3603, "Noah’s Hotels" },
            { 3604, "Отели, мотели, курорты" },
            { 3605, "Отели, мотели, курорты" },
            { 3606, "Отели, мотели, курорты" },
            { 3607, "Отели, мотели, курорты" },
            { 3608, "Отели, мотели, курорты" },
            { 3609, "Отели, мотели, курорты" },
            { 3610, "Отели, мотели, курорты" },
            { 3611, "Отели, мотели, курорты" },
            { 3612, "Movenpick Hotels" },
            { 3613, "Отели, мотели, курорты" },
            { 3614, "Отели, мотели, курорты" },
            { 3615, "Travelodge" },
            { 3616, "Отели, мотели, курорты" },
            { 3617, "Отели, мотели, курорты" },
            { 3618, "Отели, мотели, курорты" },
            { 3619, "Отели, мотели, курорты" },
            { 3620, "Telford International" },
            { 3621, "Отели, мотели, курорты" },
            { 3622, "Merlin Hotels" },
            { 3623, "Dorint Hotels" },
            { 3624, "Отели, мотели, курорты" },
            { 3625, "Hotle Universale" },
            { 3626, "Prince Hotels" },
            { 3627, "Отели, мотели, курорты" },
            { 3628, "Отели, мотели, курорты" },
            { 3629, "Dan Hotels" },
            { 3630, "Отели, мотели, курорты" },
            { 3631, "Отели, мотели, курорты" },
            { 3632, "Отели, мотели, курорты" },
            { 3633, "Rank Hotels" },
            { 3634, "Swissotel" },
            { 3635, "Reso Hotels" },
            { 3636, "Sarova Hotels" },
            { 3637, "Ramada Inns" },
            { 3638, "Ho Jo Inn" },
            { 3639, "Mount Charlotte Thistle" },
            { 3640, "Hyatt Hotel" },
            { 3641, "Sofitel Hotels" },
            { 3642, "Novotel Hotels" },
            { 3643, "Steigenberger Hotels" },
            { 3644, "Econo Lodges" },
            { 3645, "Queens Moat Houses" },
            { 3646, "Swallow Hotels" },
            { 3647, "Husa Hotels" },
            { 3648, "De Vere Hotels" },
            { 3649, "Radisson Hotels" },
            { 3650, "Red Rook Inns" },
            { 3651, "Imperial London Hotel" },
            { 3652, "Embassy Hotels" },
            { 3653, "Penta Hotels" },
            { 3654, "Loews Hotels" },
            { 3655, "Scandic Hotels" },
            { 3656, "Sara Hotels" },
            { 3657, "Oberoi Hotels" },
            { 3658, "Otani Hotels" },
            { 3659, "Taj Hotels International" },
            { 3660, "Knights Inns" },
            { 3661, "Metropole Hotels" },
            { 3662, "Отели, мотели, курорты" },
            { 3663, "Hoteles El Presidents" },
            { 3664, "Flag Inn" },
            { 3665, "Hampton Inns" },
            { 3666, "Stakis Hotels" },
            { 3667, "Отели, мотели, курорты" },
            { 3668, "Maritim Hotels" },
            { 3669, "Отели, мотели, курорты" },
            { 3670, "Arcard Hotels" },
            { 3671, "Arctia Hotels" },
            { 3672, "Campaniel Hotels" },
            { 3673, "Ibusz Hotels" },
            { 3674, "Rantasipi Hotels" },
            { 3675, "Interhotel Cedok" },
            { 3676, "Отели, мотели, курорты" },
            { 3677, "Climat De France Hotels" },
            { 3678, "Cumulus Hotels" },
            { 3679, "Danubius Hotel" },
            { 3680, "Отели, мотели, курорты" },
            { 3681, "Adams Mark Hotels" },
            { 3682, "Allstar Inns" },
            { 3683, "Отели, мотели, курорты" },
            { 3684, "Budget Host Inns" },
            { 3685, "Budgetel Hotels" },
            { 3686, "Suisse Chalets" },
            { 3687, "Clarion Hotels" },
            { 3688, "Compri Hotels" },
            { 3689, "Consort Hotels" },
            { 3690, "Courtyard By Marriott" },
            { 3691, "Dillion Inns" },
            { 3692, "Doubletree Hotels" },
            { 3693, "Drury Inns" },
            { 3694, "Economy Inns Of America" },
            { 3695, "Embassy Suites" },
            { 3696, "Exel Inns" },
            { 3697, "Farfield Hotels" },
            { 3698, "Harley Hotels" },
            { 3699, "Midway Motor Lodge" },
            { 3700, "Motel 6" },
            { 3701, "Guest Quarters (formally Pickett Suite Hotels)" },
            { 3702, "The Registry Hotels" },
            { 3703, "Residence Inns" },
            { 3704, "Royce Hotels" },
            { 3705, "Sandman Inns" },
            { 3706, "Shilo Inns" },
            { 3707, "Shoney’s Inns" },
            { 3708, "Отели, мотели, курорты" },
            { 3709, "Super8 Motels" },
            { 3710, "The Ritz Carlton Hotels" },
            { 3711, "Flag Inns (Ausralia)" },
            { 3712, "Golden Chain Hotel" },
            { 3713, "Quality Pacific Hotel" },
            { 3714, "Four Seasons Hotel (Australia)" },
            { 3715, "Farifield Inn" },
            { 3716, "Carlton Hotels" },
            { 3717, "City Lodge Hotels" },
            { 3718, "Karos Hotels" },
            { 3719, "Protea Hotels" },
            { 3720, "Southern Sun Hotels" },
            { 3721, "Hilton Conrad" },
            { 3722, "Wyndham Hotel And Resorts" },
            { 3723, "Rica Hotels" },
            { 3724, "Iner Nor Hotels" },
            { 3725, "Seaines Planation" },
            { 3726, "Rio Suites" },
            { 3727, "Broadmoor Hotel" },
            { 3728, "Bally’s Hotel And Casino" },
            { 3729, "John Ascuaga’s Nugget" },
            { 3730, "Mgm Grand Hotel" },
            { 3731, "Harrah’s Hotels And Casinos" },
            { 3732, "Opryland Hotel" },
            { 3733, "Boca Raton Resort" },
            { 3734, "Harvey/bristol Hotels" },
            { 3735, "Отели, мотели, курорты" },
            { 3736, "Colorado Belle/Edgewater Resort" },
            { 3737, "Riviera Hotel And Casino" },
            { 3738, "Tropicana Resort And Casino" },
            { 3739, "Woodside Hotels And Resorts" },
            { 3740, "Townplace Suites" },
            { 3741, "Millenium Broadway Hotel" },
            { 3742, "Club Med" },
            { 3743, "Biltmore Hotel And Suites" },
            { 3744, "Carefree Resorts" },
            { 3745, "St. Regis Hotel" },
            { 3746, "The Eliot Hotel" },
            { 3747, "Clubcorp/club Resorts" },
            { 3748, "Welesley Inns" },
            { 3749, "The Beverly Hills Hotel" },
            { 3750, "Crowne Plaza Hotels" },
            { 3751, "Homewood Suites" },
            { 3752, "Peabody Hotels" },
            { 3753, "Greenbriah Resorts" },
            { 3754, "Amelia Island Planation" },
            { 3755, "The Homestead" },
            { 3756, "South Seas Resorts" },
            { 3757, "Отели, мотели, курорты" },
            { 3758, "Отели, мотели, курорты" },
            { 3759, "Отели, мотели, курорты" },
            { 3760, "Отели, мотели, курорты" },
            { 3761, "Отели, мотели, курорты" },
            { 3762, "Отели, мотели, курорты" },
            { 3763, "Отели, мотели, курорты" },
            { 3764, "Отели, мотели, курорты" },
            { 3765, "Отели, мотели, курорты" },
            { 3766, "Отели, мотели, курорты" },
            { 3767, "Отели, мотели, курорты" },
            { 3768, "Отели, мотели, курорты" },
            { 3769, "Отели, мотели, курорты" },
            { 3770, "Отели, мотели, курорты" },
            { 3771, "Отели, мотели, курорты" },
            { 3772, "Отели, мотели, курорты" },
            { 3773, "Отели, мотели, курорты" },
            { 3774, "Отели, мотели, курорты" },
            { 3775, "Отели, мотели, курорты" },
            { 3776, "Отели, мотели, курорты" },
            { 3777, "Отели, мотели, курорты" },
            { 3778, "Отели, мотели, курорты" },
            { 3779, "Отели, мотели, курорты" },
            { 3780, "Отели, мотели, курорты" },
            { 3781, "Отели, мотели, курорты" },
            { 3782, "Отели, мотели, курорты" },
            { 3783, "Отели, мотели, курорты" },
            { 3784, "Отели, мотели, курорты" },
            { 3785, "Отели, мотели, курорты" },
            { 3786, "Отели, мотели, курорты" },
            { 3787, "Отели, мотели, курорты" },
            { 3788, "Отели, мотели, курорты" },
            { 3789, "Отели, мотели, курорты" },
            { 3790, "Отели, мотели, курорты" },
            { 3791, "Отели, мотели, курорты" },
            { 3792, "Отели, мотели, курорты" },
            { 3793, "Отели, мотели, курорты" },
            { 3794, "Отели, мотели, курорты" },
            { 3795, "Отели, мотели, курорты" },
            { 3796, "Отели, мотели, курорты" },
            { 3797, "Отели, мотели, курорты" },
            { 3798, "Отели, мотели, курорты" },
            { 3799, "Отели, мотели, курорты" },
            { 3816, "Home2Suites" },
            { 3828, "Cosmopolitan of Las Vegas" },
            { 3830, "Park Plaza Hotel" },
            { 3831, "Waldorf" },
            { 3882, "Инкассация чека (обналичивание)" },
            { 4011, "Железные дороги – перевозка грузов" },
            { 4111, "Пассажирские перевозки - пригородные и местные пригородные рейсы, включая паромы" },
            { 4112, "Пассажирские железнодорожные перевозки" },
            { 4119, "Услуги скорой помощи" },
            { 4121, "Лимузины и такси" },
            { 4131, "Автобусные линии" },
            { 4214, "Агентства по автотранспортным перевозкам, местные/ дальные автогрузоперевозки, компании попереезду и хранению, местная доставка" },
            { 4215, "Услуги курьера – по воздуху и на земле, агентство по отправке грузов" },
            { 4225, "Складское хранение общественного пользования – сельскохозяйственных продуктов, охлаждаемые продукты, хранение предметов домашнего обихода" },
            { 4304, "Категория неизвестна" },
            { 4411, "Круизные линии" },
            { 4457, "Аренда и наем суден" },
            { 4468, "Пристани для яхт, их обслуживание и поставка" },
            { 4511, "Авиалинии, авиакомпании - нигде более не классифицированные" },
            { 4582, "Аэропорты, терминалы аэропортов, лётные поля" },
            { 4722, "Туристические агентства и организаторы экскурсий" },
            { 4729, "Услуги пассажирских перевозок – нигде более не классифицированные" },
            { 4784, "Дорожный и мостовой сборы, пошлины" },
            { 4785, "Категория неизвестна" },
            { 4789, "Услуги пассажирских перевозок – нигде более не классифицированные" },
            { 4812, "Телекоммуникационное оборудование, включая продажу телефонов" },
            { 4813, "Торговые точки телеком клавишного ввода, предлагающие единичные локальные и дальние телефонные звонки, используя центральный номер доступа без разговора с оператором и используя код доступа" },
            { 4814, "Телекоммуникационные услуги" },
            { 4815, "МастерФон телефонные услуги – Ежемесячное составление телефонных счетов" },
            { 4816, "Компьютерные сети, информационные услуги" },
            { 4821, "Услуги телеграфа" },
            { 4829, "Денежные переводы" },
            { 4899, "Кабельные и другие платные телевизионные услуги" },
            { 4900, "Коммунальные услуги – электричество, газ, канализация, вода" },
            { 5013, "Поставщики грузовиков и запчастей" },
            { 5021, "Офисная и торговая мебель" },
            { 5039, "Строительные материалы – нигде более не классифицированные" },
            { 5044, "Офисное, фотографическое, фотокопировальное, и микрофильмирующее оборудование" },
            { 5045, "Компьютеры, периферийное компьютерное оборудование, программное обеспечение" },
            { 5046, "Коммерческое оборудование – нигде более не классифицированное" },
            { 5047, "Стоматологическое / лабораторное / медицинское / офтальмологическое оборудование и материалы для больниц" },
            { 5051, "Центры и офисы работ по металлу" },
            { 5065, "Электрические части и оборудование" },
            { 5072, "Оборудование и сопутствующие материалы для технического обеспечения" },
            { 5074, "Оборудование для водопровода и отопительной системы" },
            { 5085, "Промышленное оборудование –нигде более не классифицированное" },
            { 5094, "Драгоценные камни и металлы, часы и ювелирные изделия" },
            { 5099, "Товары длительного пользования – нигде более не классифицированные" },
            { 5111, "Канцелярия, офисные сопутствующие товары, бумага для печатания и письма" },
            { 5122, "Лекарства, их распространители, аптеки" },
            { 5131, "Штучные товары, галантерея и другие текстильные товары" },
            { 5137, "Мужская, женская и детская спецодежда" },
            { 5139, "Спец-обувь" },
            { 5169, "Химикалии и смежные вещества - нигде более не классифицированные" },
            { 5172, "Нефть и нефтепродукты" },
            { 5192, "Книги, периодические издания и газеты" },
            { 5193, "Принадлежности для флористов, питомник и цветы" },
            { 5198, "Лакокрасочная продукция и сопровождающие товары" },
            { 5199, "Товары недлительного пользования - нигде более не классифицированные" },
            { 5200, "Товары для дома" },
            { 5211, "Лесо- и строительный материал" },
            { 5231, "Розничная продажа стекла, красок и обоев" },
            { 5251, "Скобяные товары в розницу" },
            { 5261, "Садовые принадлежности (в том числе для ухода за газонами) в розницу" },
            { 5271, "Продажа жилых фургонов" },
            { 5292, "Категория неизвестна" },
            { 5295, "Категория неизвестна" },
            { 5297, "Retail Internet Volume" },
            { 5298, "Internet Shopping Grocery Store" },
            { 5300, "Оптовики" },
            { 5309, "Беспошлинные магазины Duty Free" },
            { 5310, "Магазины, торгующие по сниженным ценам" },
            { 5311, "Универмаги" },
            { 5331, "Универсальные магазины" },
            { 5399, "Различные товары общего назначения" },
            { 5411, "Бакалейные магазины, супермаркеты" },
            { 5412, "Гибридные супермаркеты" },
            { 5415, "Категория неизвестна" },
            { 5422, "Продажа свежего и мороженого мяса" },
            { 5441, "Кондитерские" },
            { 5451, "Продажа молочных продуктов в розницу" },
            { 5462, "Булочные" },
            { 5499, "Различные продовольственные магазины - нигде более не классифицированные" },
            { 5511, "Легковой и грузовой транспорт – продажа, сервис, ремонт, запчасти и лизинг." },
            { 5521, "Продажа легковых и грузовых автомобилей (только подержанных)" },
            { 5531, "Автомагазины и товары для дома" },
            { 5532, "Автошины" },
            { 5533, "Автозапчасти и аксессуары" },
            { 5541, "Станции техобслуживания, с дополнительными услугами или без" },
            { 5542, "Автоматизированные бензозаправки" },
            { 5551, "Продажа лодок" },
            { 5561, "Дома- автоприцепы, жилые неразборные и грузовые прицепы" },
            { 5571, "Продажа мотоциклов" },
            { 5592, "Продажа домов на колесах" },
            { 5598, "Продажа снегоходов" },
            { 5599, "Продажа различного рода автомобилей, авиа- и с/х оборудования - нигде более не классифицированные" },
            { 5611, "Мужская одежда и аксессуары, включая одежду для мальчиков" },
            { 5621, "Готовая женская одежда" },
            { 5631, "Аксессуары для женщин" },
            { 5641, "Детская одежда, включая одежду для самых маленьких" },
            { 5651, "Одежда для всей семьи" },
            { 5655, "Спортивная одежда, одежда для верховой езды и езды на мотоцикле" },
            { 5661, "Обувные магазины" },
            { 5681, "Изготовление и продажа меховых изделий" },
            { 5691, "Магазины мужской и женской одежды" },
            { 5697, "Услуги по переделке, починке и пошиву одежды" },
            { 5698, "Парики и накладки из искусственных волос" },
            { 5699, "Различные магазины одежды и аксессуаров" },
            { 5712, "Оборудование, мебель и бытовые принадлежности (кроме электрооборудования)" },
            { 5713, "Покрытия для пола" },
            { 5714, "Ткани, обивочный материал, гардины и портьеры, жалюзи" },
            { 5715, "Оптовые продавцы алкоголя" },
            { 5718, "Продажа каминов, экранов для каминов и аксессуаров" },
            { 5719, "Различные специализированные магазины бытовых принадлежностей" },
            { 5722, "Бытовое оборудование" },
            { 5732, "Продажа электронного оборудования" },
            { 5733, "Продажа музыкальных инструментов, фортепиано, нот." },
            { 5734, "Продажа компьютерного программного обеспечения" },
            { 5735, "Магазины звукозаписи" },
            { 5811, "Поставщики провизии" },
            { 5812, "Места общественного питания, рестораны" },
            { 5813, "Бары, коктейль-бары, дискотеки, ночные клубы и таверны – места продажи алкогольных напитков" },
            { 5814, "Фастфуд" },
            { 5815, "Цифровые товары - аудиовизуальные медиа, включая книги, фильмы и музыку" },
            { 5816, "Цифровые товары – игры" },
            { 5817, "Цифровые товары - приложения (кроме игр)" },
            { 5818, "Цифровые товары - мультикатегория" },
            { 5912, "Аптеки" },
            { 5921, "Магазины с продажей спиртных напитков навынос" },
            { 5931, "Секонд-хенды, магазины б/у товаров, комиссионки" },
            { 5932, "Антикварные магазины – продажа, ремонт и услуги реставрации" },
            { 5933, "Ломбарды" },
            { 5935, "Уничтожение и сбор остатков" },
            { 5937, "Магазины репродукций и антиквариата" },
            { 5940, "Веломагазины – продажа и обслуживание" },
            { 5941, "Спорттовары" },
            { 5942, "Книжные магазины" },
            { 5943, "Магазины офисных, школьных принадлежностей, канцтоваров" },
            { 5944, "Часы, ювелирные и серебряные изделия" },
            { 5945, "Игрушки, игры и хобби-товары" },
            { 5946, "Магазины фотооборудования и фотоприборов" },
            { 5947, "Магазины открыток, подарков, новинок и сувениров" },
            { 5948, "Магазины кожаных изделий, дорожных принадлежностей" },
            { 5949, "Магазины ткани, ниток, рукоделия, шитья" },
            { 5950, "Магазины хрусталя и изделий из стекла" },
            { 5960, "Прямой маркетинг – страховые услуги" },
            { 5961, "Заказы по почте, включая заказы по каталогу" },
            { 5962, "Прямой маркетинг – услуги, относящиеся к туризму" },
            { 5963, "Продажа \"от двери до двери\"" },
            { 5964, "Прямой маркетинг – торговля по каталогам" },
            { 5965, "Прямой маркетинг – комбинированный каталог и розничные продавцы" },
            { 5966, "Прямой маркетинг - исходящий телемаркетинг" },
            { 5967, "Прямой маркетинг – входящий телемаркетинг" },
            { 5968, "Прямой маркетинг – Торговые точки подписки" },
            { 5969, "Прямой маркетинг – другие торговые точки прямого маркетинга (нигде более не классифицированные)" },
            { 5970, "Магазины художественных и ремесляных изделий" },
            { 5971, "Галереи и художественные посредники" },
            { 5972, "Магазины монет и марок (филателические и нумизматические)" },
            { 5973, "Магазины религиозных товаров" },
            { 5975, "Слуховые аппараты – продажа, сервис, снабжение" },
            { 5976, "Ортопедические товары" },
            { 5977, "Магазины косметики" },
            { 5978, "Магазины печатающих устройств – аренда, продажа, услуги" },
            { 5983, "Горючее топливо – уголь, мазут, сжиженная нефть, древесина" },
            { 5992, "Флористика" },
            { 5993, "Табачные магазины" },
            { 5994, "Дилеры по продаже печатной продукции" },
            { 5995, "Зоомагазины" },
            { 5996, "Плавательные бассейны – продажа и снабжение" },
            { 5997, "Магазины электрических бритвенных принадлежностей – распродажа и услуги." },
            { 5998, "Магазины палаток и навесов" },
            { 5999, "Различные магазины и специальные розничные магазины" },
            { 6010, "Финансовые учреждения – снятие наличности вручную" },
            { 6011, "Финансовые учреждения – снятие наличности автоматически" },
            { 6012, "Финансовые учреждения – торговля и услуги" },
            { 6022, "Financial Institution (RCL Internal)" },
            { 6023, "State Banks (RCL Internal)" },
            { 6025, "National Banks (RCL Internal)" },
            { 6026, "National Banks Non Federal (RCL Internal)" },
            { 6028, "Unincorporated Private Banks (RCL Internal)" },
            { 6050, "Финансовые учреждения – квази-кэш" },
            { 6051, "Нефинансовые учреждения – квази-кэш" },
            { 6211, "Ценные бумаги – Брокеры/Дилеры" },
            { 6300, "Продажа страхования, андеррайтинг, премии" },
            { 6381, "Страховые премии" },
            { 6399, "Страхование - нигде более не классифицированные" },
            { 6513, "Агенты недвижимости и менеджеры - Аренда" },
            { 6529, "Remote Stored Value Load - Финансовые организации" },
            { 6530, "Remote Stored Value Load - Продавец" },
            { 6531, "Оплата услуг – денежные переводы" },
            { 6532, "Платежная операция - финансовое учреждение" },
            { 6533, "Платежная операция - продавец" },
            { 6534, "Денежный перевод - финансовое учреждение" },
            { 6535, "Права требования на ценности — Финансовые организации" },
            { 6536, "Денежные переводы MasterCard MoneySend - внутри страны" },
            { 6537, "Денежные переводы MasterCard MoneySend - между странами" },
            { 6538, "Денежные переводы MasterCard MoneySend Funding" },
            { 6539, "Транзакция по финансированию (исключая MoneySend)" },
            { 6540, "Транзакции по финансированию POI (за исключением MoneySend)" },
            { 6611, "Переплата (авансовые платежи)" },
            { 6760, "Облигации сберегательного займа" },
            { 7011, "Отели и мотели - нигде более не классифицированные" },
            { 7012, "Тайм-шер" },
            { 7032, "Рекреационные и спортивные лагеря" },
            { 7033, "Кемпинги и трейлер-парки" },
            { 7210, "Услуги по уборке и прачечной" },
            { 7211, "Услуги прачечной - семейные и коммерческие" },
            { 7216, "Химчистка" },
            { 7217, "Чистка ковров и обивок" },
            { 7221, "Фотостудии" },
            { 7230, "Парикмахерские и салоны красоты" },
            { 7251, "Чистка шляп, ремонт и чистка обуви" },
            { 7261, "Похоронные службы и крематории" },
            { 7273, "Знакомства" },
            { 7276, "Служба налоговой подготовки" },
            { 7277, "Долги, брак, личные вопросы - консультирование" },
            { 7278, "Услуги покупок/шоппинга" },
            { 7280, "Пациент больницы – вывод личных средств" },
            { 7296, "Сдача в аренду костюмов, униформы, простой одежды" },
            { 7297, "Массажные салоны" },
            { 7298, "Салоны красоты и здоровья" },
            { 7299, "Различные услуги - нигде более не классифицированные" },
            { 7311, "Рекламные услуги" },
            { 7321, "Потребительские кредитные агентства" },
            { 7322, "Агентства взыскания долгов" },
            { 7332, "Услуги синьки и фотокопирования" },
            { 7333, "Коммерческое искусство, графика, фотография" },
            { 7338, "Быстрое копирование, репродуцирование и услуги по созданию чертежей" },
            { 7339, "Услуги стенографии и секретарского дела" },
            { 7342, "Истребление насекомых и дезинфекция" },
            { 7349, "Уборка и чистка помещений" },
            { 7361, "Агентства по трудоустройству, временные справочные службы" },
            { 7372, "Программирование, обработка данных, проектирование интегрированных систем" },
            { 7375, "Информационно-поисковые услуги" },
            { 7379, "Ремонт компьютеров" },
            { 7389, "Бизнес услуги – нигде более не классифицированные" },
            { 7392, "Услуги по консультированию, управлению и связям с общественностью" },
            { 7393, "Детективные агентства, охранные агентства, службы безопасности, включая бронированные автомобили, сторожевых собак" },
            { 7394, "Аренда оборудования и лизинговые услуги, аренда мебели, прокат инструментов" },
            { 7395, "Фотостудии, фотолаборатории" },
            { 7399, "Бизнес услуги – нигде более не классифицированные" },
            { 7511, "Стоянка грузового транспорта" },
            { 7512, "Прокат автомобилей" },
            { 7513, "Прокат аксессуаров для трэйлеров и грузовиков." },
            { 7519, "Прокат домиков на колесах, аксессуары к наземному транспорту." },
            { 7523, "Паркинги и гаражи" },
            { 7531, "Станции технического обслуживания для автомобильного транспорта" },
            { 7534, "Шиномонтаж и вулканизация" },
            { 7535, "Покраска автомобилей" },
            { 7538, "СТО общего назначения" },
            { 7542, "Автомойки" },
            { 7549, "Буксировка" },
            { 7622, "Ремонт электроники" },
            { 7623, "Ремонт кондиционеров и холодильников" },
            { 7629, "Ремонт электрооборудования и малой бытовой техники" },
            { 7631, "Центры ремонта часов и чистки ювелирных изделий" },
            { 7641, "Мебель – обивка, ремонт и реставрация" },
            { 7692, "Ремонт с помощью сварки" },
            { 7699, "Ремонтные услуги – нигде более не классифицированные" },
            { 7800, "Правительственная лотерея (только США)" },
            { 7801, "Азартные игры в интернете (только США)" },
            { 7802, "Лошадиные / собачьи бега (только США)" },
            { 7829, "Производство фото/видео" },
            { 7832, "Кинотеатры" },
            { 7833, "Экспресс-оплата – Кинотеатр" },
            { 7841, "Видеопрокат" },
            { 7911, "Танцклубы, танцшколы и студии" },
            { 7922, "Театральные продюсеры (кроме кинофильмов), билетные агентства" },
            { 7929, "Музыкальные группы, оркестры и прочие развлекательные услуги" },
            { 7932, "Бильярд-клубы" },
            { 7933, "Боулинг-клубы" },
            { 7941, "Атлетические поля, коммерческие виды спорта, профессиональные спортивные клубы, промоутеры спорта" },
            { 7991, "Туристические аттракционы и шоу" },
            { 7992, "Публичные поля для гольфа" },
            { 7993, "Принадлежности для видеоигр" },
            { 7994, "Галереи/учреждения видеоигр" },
            { 7995, "Транзакции по азартным играм" },
            { 7996, "Парки аттракционов, карнавалы, цирки, гадалки" },
            { 7997, "Клубы – загородные клубы, членство (отдых, спорт), частные поля для гольфа" },
            { 7998, "Аквариумы, дельфинарии, зоопарки и морские парки" },
            { 7999, "Услуги отдыха — нигде более не классифицированные" },
            { 8011, "Доктора — нигде более не классифицированные" },
            { 8021, "Дантисты, ортодантисты" },
            { 8031, "Остеопаты" },
            { 8041, "Хиропрактики" },
            { 8042, "Оптометристы, офтальмологи" },
            { 8043, "Оптика, оптические товары и очки" },
            { 8044, "Оптика, оптические товары и очки" },
            { 8049, "Ортопеды" },
            { 8050, "Услуги персонального ухода" },
            { 8062, "Больницы" },
            { 8071, "Стоматологические и медицинские лаборатории" },
            { 8099, "Медицинские работники, медицинские услуги – нигде более не классифицированные" },
            { 8111, "Адвокаты, юридические услуги" },
            { 8211, "Начальная и средняя школы" },
            { 8220, "Колледжи, университеты" },
            { 8241, "Дистанционные школы" },
            { 8244, "Бизнес / секретарские школы" },
            { 8249, "Профессиональные / торговые школы" },
            { 8299, "Образовательные услуги" },
            { 8351, "Дошкольные заведения" },
            { 8398, "Благотворительные и общественные службы - сбор средств" },
            { 8641, "Гражданские, социальные и братские ассоциации" },
            { 8651, "Политические организации" },
            { 8661, "Религиозные организации" },
            { 8664, "Категория неизвестна" },
            { 8675, "Автомобильные ассоциации" },
            { 8699, "Членские организации – нигде более не классифицированные" },
            { 8734, "Испытательные лаборатории (немедицинские)" },
            { 8911, "Архитектурные, инженерные и геодезические услуги" },
            { 8931, "Бухгалтерский учет, аудит и бухгалтерские услуги" },
            { 8999, "Профессиональные услуги - нигде более не классифицированные" },
            { 9034, "I-Purchasing Pilot" },
            { 9211, "Судебные выплаты, включая алименты и детскую поддержку" },
            { 9222, "Штрафы" },
            { 9223, "Платежи по залогам и облигациям" },
            { 9311, "Налоговые платежи" },
            { 9399, "Правительственные услуги - нигде более не классифицированные" },
            { 9401, "I-Purchasing Pilot" },
            { 9402, "Почтовые услуги (только правительственные)" },
            { 9405, "Внутриправительственные закупки - только правительственные" },
            { 9411, "Платежи по государственному займу" },
            { 9700, "Automated Referral Service (только VISA)" },
            { 9701, "Служба проверки учетных данных Visa (только VISA)" },
            { 9702, "Аварийные службы (GCAS) (только VISA)" },
            { 9751, "Великобритания. Универсамы. Электронный Горячий Файл" },
            { 9752, "Британские Бензозаправочные станции. Электронный Горячий Файл" },
            { 9754, "Лошадиные / собачьи бега (только США)" },
            { 9950, "Покупки внутри компании" },
            { 9999, "Категория неизвестна" }
        };
    }

    public static string GetCodeDescription( int mcc )
    {
        if ( CodeDescription.TryGetValue( mcc, out var description ) )
            return description;

        return "Неизвестный код MCC " + mcc;
    }
}